[package]
name = "cfworker-template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.3"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
