name: Deploy to production

env:
  PROJECT_NAME: qr

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-front.yml"
      - "frontend/package.json"
      - "frontend/tsconfig.json"
      - "frontend/src/**"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1
      - name: Install Deps
        run: bun --cwd frontend/ install

      - name: Build
        run: bun --cwd frontend/ build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        # env:
        # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
        # YOUR_OTHER_SECRET: ${{ secrets.YOUR_OTHER_SECRET }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "frontend"
          command: pages deploy ./frontend/dist --project-name "${{ env.PROJECT_NAME }}"
          # secrets: |
          #   YOUR_SECRET
          #   YOUR_OTHER_SECRET
